---
title: "Markdown"
author: "Rory King"
date: "2022-11-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

CreditData <- read.csv("creditData.csv", header = TRUE)

head(CreditData, 10)

library(dplyr)
library(rpart)
library(rpart.plot)
library(caret)
library(randomForest)
library(car)
```

```{r}
table(CreditData$TARGET)

head(CreditData, 10)

```

```{r}
names(CreditData)

# then removing unnecesary variables

#CreditData <- CreditData[ , -c(1:2, 4:42, 62:68)]

CreditData <- CreditData[ , -c(1:2, 6, 8 , 10:13, 15, 16, 20, 21:28, 30, 32:40, 42:68)]
names(CreditData)
```

```{r}
#recoding so target data is now low and high
CreditData$TARGET <- recode(CreditData$TARGET,
                         "1" = "High",
                         "0" = "Low")

CreditData$TARGET <- as.factor(CreditData$TARGET)
```

```{r}
# Setting up T and V splits

set.seed(666)

train_index <- sample(1:nrow(CreditData), 0.7 * nrow(CreditData))
valid_index <- setdiff(1:nrow(CreditData), train_index)

train_df <- CreditData[train_index, ]
valid_df <- CreditData[valid_index, ]

```

```{r}
#now Setting up class tree

class_tr <- rpart( TARGET ~ FLAG_OWN_REALTY + AMT_INCOME_TOTAL + AMT_CREDIT ,    data = train_df, method = "class", minbucket = 100,
                  maxdepth = 30)

rpart.plot(class_tr, type = 4)
```
```{r}
printcp(class_tr2)
```

```{r}
class_tr2 <- rpart( TARGET ~ .,
                    data = train_df, method = "class", control = rpart.control(minsplit = 200,  minbucket = 30, cp = 0.00005))

rpart.plot(class_tr2, type = 4)
```

```{r}
class_tr_train_predict <- predict(class_tr2, train_df,
                                  type = "class")

#confusionMatrix(class_tr_train_predict, train_df$TARGET, positive = "High")
confusionMatrix(class_tr_train_predict,as.factor(train_df$TARGET), positive = "1")
```

```{r}
class_tr_rf <- randomForest(TARGET ~ AMT_INCOME_TOTAL + DAYS_BIRTH + DAYS_EMPLOYED + NAME_HOUSING_TYPE , 
                            data = train_df, ntree = 200,
                            nodesize = 5, importance = TRUE)

class_tr_rf_pred <- predict(class_tr_rf, valid_df)
confusionMatrix(class_tr_rf_pred, valid_df$TARGET, positive = "High")
```

kNN attempt

```{r}
#adding new df
test_df <- data.frame(NAME_CONTRACT_TYPE = 'Cash Loans',
                      FLAG_OWN_CAR = 'Y',
                      FLAG_OWN_REALTY = 'Y',
                      CNT_CHILDREN = 3,
                      AMT_INCOME_TOTAL = 145000,
                      AMT_CREDIT = 285000,
                      NAME_INCOME_TYPE = 'Working',
                      NAME_EDUCATION_TYPE = 'Higher education',
                      NAME_HOUSING_TYPE = 'House / apartment',
                      DAYS_EMPLOYED = 32000,
                      DAYS_ID_PUBLISH = -1456,
                      OCCUPATION_TYPE = 'sales staff',
                      ORGANIZATION_TYPE = 'medicine')

test_df
```


```{r}
#Normalizing

train_norm <- train_df
valid_norm <- valid_df

norm_values <- preProcess(train_df[, -c(1)],
                          method = c("center",
                                     "scale"))
train_norm[, -c(1)] <- predict(norm_values,
                                train_df[, -c(1)])

head(train_norm)

```

```{r}
valid_norm[, -c(1)] <- predict(norm_values,
                                valid_df[, -c(1)])

head(valid_norm)
```

```{r}
knn_model_7 <- caret::knn3(TARGET ~ ., data = train_norm, k = 9)
knn_model_7
```

```{r}
knn_model_7_valid <- caret::knn3(TARGET ~., data = valid_norm, k = 9)
knn_model_7_valid
```

```{r}
knn_prediction <- predict(knn_model_7, newdata = train_norm[, -c(1)], type = "class")
head(knn_prediction)

```

